version: "3.3"
services:
 node:
  image: "node:17-alpine"
  user: "node"
  working_dir: /home/augusto/Documentos/Proyectos/Personal/Node/veterinaria
  ports:
      - "3000:3000"
  volumes:
      - ./:/home/augusto/Documentos/Proyectos/Personal/Node/veterinaria
  command: sh -c "npm init -y && node index.js "
